import type {
  Activity,
  Article,
  FileAsset,
  ForumThread,
  Group,
  Member,
  NewsCategory,
  NewsItem,
  Product,
} from './types';

export const products: Product[] = [
  {
    name: 'Snail Mucin Dew Essence',
    slug: 'snail-mucin-dew-essence',
    category: 'Beauty',
    categorySlug: 'beauty',
    sku: 'ASI-SME-120',
    price: 32,
    image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640167/asiance/site-assets/products/snail-mucin-dew-essence-png.png',
    badge: 'new',
    description: 'A silky daily essence with snail mucin and humectants for cushioned hydration and a fresh dewy finish.',
    shortDescription: 'Silky hydrating daily essence.',
    stock: 49,
    stockManagement: true,
    stockStatus: 'instock',
    status: 'active',
    createdAt: '2026-07-31T14:30:07.000Z',
  },
  {
    name: 'Camellia Glow Hair Oil',
    slug: 'camellia-glow-hair-oil',
    category: 'Beauty',
    categorySlug: 'beauty',
    sku: 'ASI-CAM-80',
    price: 30,
    image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640167/asiance/site-assets/products/camellia-glow-hair-oil-png.png',
    badge: 'new',
    description: 'A lightweight golden camellia oil that smooths dry ends, softens shine, and finishes without heaviness.',
    shortDescription: 'Lightweight golden finishing oil.',
    stock: 43,
    stockManagement: true,
    stockStatus: 'instock',
    status: 'active',
    createdAt: '2026-07-31T14:30:06.000Z',
  },
  {
    name: 'Cloud Milk Toner',
    slug: 'cloud-milk-toner',
    category: 'Beauty',
    categorySlug: 'beauty',
    sku: 'ASI-CMT-150',
    price: 34,
    image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640165/asiance/site-assets/products/cloud-milk-toner-png.png',
    badge: 'new',
    description: 'A cushiony milky toner that layers lightweight hydration and leaves skin feeling soft and balanced.',
    shortDescription: 'Softening daily milky toner.',
    stock: 52,
    stockManagement: true,
    stockStatus: 'instock',
    status: 'active',
    createdAt: '2026-07-31T14:30:05.000Z',
  },
  {
    name: 'Rose Peptide Mask',
    slug: 'rose-peptide-mask',
    category: 'Beauty',
    categorySlug: 'beauty',
    sku: 'ASI-RPM-50',
    price: 28,
    image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640167/asiance/site-assets/products/rose-peptide-mask-png.png',
    badge: 'new',
    description: 'A cooling rose gel mask with peptides and humectants for a smooth, hydrated, rested-looking finish.',
    shortDescription: 'Cooling rose peptide gel mask.',
    stock: 47,
    stockManagement: true,
    stockStatus: 'instock',
    status: 'active',
    createdAt: '2026-07-31T14:30:04.000Z',
  },
  {
    name: 'Heartleaf Balancing Toner',
    slug: 'heartleaf-balancing-toner',
    category: 'Beauty',
    categorySlug: 'beauty',
    sku: 'ASI-HRT-200',
    price: 26,
    image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640168/asiance/site-assets/products/heartleaf-balancing-toner-png.png',
    badge: 'new',
    description: 'A lightweight heartleaf toner that refreshes, calms, and prepares skin for the rest of a daily routine.',
    shortDescription: 'A clear calming heartleaf toner.',
    stock: 64,
    stockManagement: true,
    stockStatus: 'instock',
    status: 'active',
    createdAt: '2026-07-31T14:30:03.000Z',
  },
  {
    name: 'Dew Lip Glow Duo',
    slug: 'dew-lip-glow-duo',
    category: 'Beauty',
    categorySlug: 'beauty',
    sku: 'ASI-LIP-DUO',
    price: 36,
    image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640165/asiance/site-assets/products/dew-lip-glow-duo-png.png',
    badge: 'new',
    description: 'A sheer rose balm and glassy gloss pairing for comfortable color and a softly polished finish.',
    shortDescription: 'Sheer rose balm and gloss duo.',
    stock: 58,
    stockManagement: true,
    stockStatus: 'instock',
    status: 'active',
    createdAt: '2026-07-31T14:30:02.000Z',
  },
  {
    name: 'Blush Satin Sleep Pair',
    slug: 'blush-satin-sleep-pair',
    category: 'Home',
    categorySlug: 'home',
    sku: 'ASI-SATIN-PAIR',
    price: 42,
    image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640165/asiance/site-assets/products/blush-satin-sleep-pair-png.png',
    badge: 'new',
    description: 'A silky pair of blush pillowcases designed to reduce overnight friction and elevate the evening wind-down.',
    shortDescription: 'Two soft blush satin pillowcases.',
    stock: 36,
    stockManagement: true,
    stockStatus: 'instock',
    status: 'active',
    createdAt: '2026-07-31T14:30:01.000Z',
  },
  {
    name: 'The silk slip dress',
    slug: 'the-silk-slip-dress',
    category: 'Essentials',
    price: 320,
    image: 'https://picsum.photos/seed/asiance-fashion-1/900/700',
    badge: 'new',
    description: 'Bias-cut silk with a quiet neckline and enough structure for day or evening.',
    stock: 18,
  },
  {
    name: 'Amber serum no. 03',
    slug: 'amber-serum-no-03',
    category: 'Apothecary',
    price: 88,
    image: 'https://picsum.photos/seed/asiance-object-4/900/700',
    description: 'A lightweight botanical serum for a slow, luminous morning routine.',
    stock: 44,
  },
  {
    name: 'Ceramic carafe',
    slug: 'ceramic-carafe',
    category: 'Objects',
    price: 145,
    image: 'https://picsum.photos/seed/asiance-object-1/900/700',
    badge: 'limited',
    description: 'Hand-glazed stoneware with a soft silhouette for bedside water or table rituals.',
    stock: 9,
  },
  {
    name: 'Slow ritual candle',
    slug: 'slow-ritual-candle',
    category: 'Apothecary',
    price: 64,
    image: 'https://picsum.photos/seed/asiance-object-2/900/700',
    description: 'Cedar, rose, and clean smoke poured into a reusable ceramic vessel.',
    stock: 31,
  },
  {
    name: 'Brass pendant lamp',
    slug: 'brass-pendant-lamp',
    category: 'Objects',
    price: 320,
    image: 'https://picsum.photos/seed/asiance-interior-1/900/700',
    description: 'A warm brass pendant for corners, reading rooms, and softer evenings.',
    stock: 12,
  },
  {
    name: 'Woven basket bag',
    slug: 'woven-basket-bag',
    category: 'Accessories',
    price: 195,
    image: 'https://picsum.photos/seed/asiance-bag-1/900/700',
    badge: 'restock',
    description: 'Market-ready woven raffia with leather handles and a generous interior.',
    stock: 24,
  },
  {
    name: 'Night repair elixir',
    slug: 'night-repair-elixir',
    category: 'Apothecary',
    price: 96,
    image: 'https://picsum.photos/seed/asiance-object-3/900/700',
    description: 'A restorative oil-serum hybrid for the end of long city days.',
    stock: 29,
  },
  {
    name: 'Rosehip facial oil',
    slug: 'rosehip-facial-oil',
    category: 'Apothecary',
    price: 72,
    image: 'https://picsum.photos/seed/asiance-object-5/900/700',
    badge: 'new',
    description: 'Pressed rosehip and meadowfoam in a small amber bottle.',
    stock: 51,
  },
];

export const articles: Article[] = [
  {
    title: 'Sandy Liang: Soft. Feminine. Unapologetically Her.',
    slug: 'sandy-liang-soft-feminine-unapologetically-her',
    category: 'Fashion and Beauty',
    excerpt: 'The designer redefining modern femininity, one bow at a time.',
    content:
      '<p>In a fashion world that often celebrates the loudest voice in the room, Sandy Liang is quietly building something lasting. Her designs are soft, romantic, and deeply personal, and they have become a uniform for a new generation of women who dress for themselves.</p><blockquote>I design clothes that I want to wear, that make me feel like myself, just the best version of me.</blockquote><h2>From Downtown Girl to Fashion Force</h2><p>Born and raised in the Lower East Side, Sandy Liang grew up surrounded by art, attitude, and authenticity. After studying at Parsons, she launched her namesake label in 2014 and quickly built a world where nostalgia feels sharp, modern, and completely wearable.</p><img src="/blog/sandy-liang-look-strip.png" alt="Pink bow dresses and accessories inspired by Sandy Liang" /><h2>The Liang Girl</h2><p>There is a distinct charm to a Sandy Liang girl. She is playful but polished, nostalgic but now. Think delicate bows, pearl details, sheer layers, and a whole lot of heart.</p><h2>Creative Process</h2><p>Liang often starts with memory: school uniforms, Chinatown storefronts, downtown walks, and the emotional shorthand of a ribbon or a perfect flat. The result is clothing that feels familiar without becoming sentimental.</p><h2>Representation Matters</h2><p>Her work carries the ease of a designer who does not flatten identity into a theme. Instead, she lets specificity lead. The clothes speak through personal references, city energy, and the confidence of an Asian American designer building her own visual language.</p><h2>What\'s Next</h2><p>The next chapter looks softer, sharper, and even more expansive. As Liang continues to grow, the bow remains less of a decoration than a signature: a small, unapologetic mark of girlhood, agency, and style.</p>',
    image: '/blog/sandy-liang-hero.png',
    authorName: 'Jaymie Moran',
    tags: ['fashion', 'designers', 'street style', 'shop the look'],
    featured: true,
    status: 'published',
    publishedAt: '2026-08-18T13:30:00.000Z',
  },
  {
    title: 'A Five-Minute Skin Reset for Humid Summer Mornings',
    slug: 'five-minute-skin-reset-humid-mornings',
    category: 'Fashion & Beauty',
    excerpt:
      'A lighter morning ritual built around comfortable layers, a fresh finish, and products that earn their place.',
    content:
      '<p>On hot, humid mornings, more product rarely feels like more care. A useful routine can be short, comfortable, and easy to repeat.</p><h2>Begin with a gentle refresh</h2><p>Use the cleansing step that leaves your skin feeling comfortable rather than tight.</p><h2>Build hydration in thin layers</h2><p>Choose one lightweight hydrating layer and give it a moment to settle.</p><h2>Finish with daily sun protection</h2><p>Use a broad-spectrum sunscreen that feels pleasant enough to apply consistently.</p>',
    image:
      'https://res.cloudinary.com/ux81wsbq/image/upload/v1785521190/asiance/library/summer-skin-reset_aql7cz.png',
    authorName: 'Asiance Editors',
    tags: ['beauty', 'skincare', 'summer'],
    featured: true,
    status: 'published',
    publishedAt: '2026-07-31T18:08:00.000Z',
  },
  {
    title: 'How to Plan an Intimate Garden Wedding That Feels Like You',
    slug: 'intimate-garden-wedding-that-feels-like-you',
    category: 'Weddings',
    excerpt:
      'A thoughtful guide to smaller guest lists, meaningful details, and an outdoor celebration with room to breathe.',
    content:
      '<p>An intimate wedding is not a smaller version of a large event. It is an opportunity to make every choice feel more personal.</p><h2>Start with the feeling</h2><p>Agree on three words that describe the celebration you want.</p><h2>Let the guest list shape the space</h2><p>Choose a garden that feels comfortable at your actual guest count.</p><h2>Protect a little unscheduled time</h2><p>Leave space after the ceremony to greet people, take a breath, and notice the day.</p>',
    image:
      'https://res.cloudinary.com/ux81wsbq/image/upload/v1785521214/asiance/library/intimate-garden-wedding_asu3hs.png',
    authorName: 'Mina Park',
    tags: ['weddings', 'planning', 'celebration'],
    featured: true,
    status: 'published',
    publishedAt: '2026-07-31T18:07:00.000Z',
  },
  {
    title: 'The Calm Nursery: Small Changes for a Gentler Bedtime',
    slug: 'calm-nursery-small-changes-gentler-bedtime',
    category: 'Family',
    excerpt:
      'Simple ways to lower visual noise, prepare the room early, and create a bedtime rhythm the whole family can recognize.',
    content:
      '<p>A calm nursery does not need a complete redesign. Small changes to light, storage, and routine can make the room easier to use.</p><h2>Prepare the room early</h2><p>Refill essentials and clear the path around the crib before bedtime begins.</p><h2>Lower the visual volume</h2><p>Keep main surfaces mostly clear and group small items inside simple containers.</p><h2>Keep safety guidance central</h2><p>Arrange the sleep space according to current guidance from your pediatrician and local health authority.</p>',
    image:
      'https://res.cloudinary.com/ux81wsbq/image/upload/v1785521235/asiance/library/calm-nursery-bedtime_moeits.png',
    authorName: 'Leah Chen',
    tags: ['family', 'nursery', 'routines'],
    featured: true,
    status: 'published',
    publishedAt: '2026-07-31T18:06:00.000Z',
  },
  {
    title: 'How to Make Room for Better Conversations',
    slug: 'make-room-for-better-conversations',
    category: 'Relationships',
    excerpt:
      'Four simple habits that turn everyday check-ins into conversations where both people feel heard.',
    content:
      '<p>Good conversation is less about finding perfect words and more about creating the conditions for attention.</p><h2>Choose a moment with enough room</h2><p>Ask whether now is a good time, or agree on a moment when neither person needs to multitask.</p><h2>Listen for the request underneath</h2><p>Before offering advice, ask whether the other person wants ideas, help, or simply company.</p><h2>End with one clear next step</h2><p>A small agreement or a simple expression of care can be enough to move forward together.</p>',
    image:
      'https://res.cloudinary.com/ux81wsbq/image/upload/v1785521261/asiance/library/better-conversations_bkfzap.png',
    authorName: 'Sophie Tran',
    tags: ['relationships', 'communication', 'connection'],
    featured: true,
    status: 'published',
    publishedAt: '2026-07-31T18:05:00.000Z',
  },
  {
    title: 'Should you try gentle contrast therapy?',
    slug: 'gentle-contrast-therapy',
    category: 'Sex & Health',
    excerpt:
      'A measured guide to hot, cold, and the ritual in between, with notes from bathhouse founders and clinicians.',
    content:
      'Contrast therapy has become a social ritual as much as a recovery tool. Start gently, keep the temperature shifts moderate, and listen closely to your body. The best version is less about extremes and more about presence: a few minutes of heat, a brief cool rinse, and a calm transition back to room temperature. Members in the circle use it as a reset, a way to mark the end of work, and a tiny act of attention.',
    image: 'https://picsum.photos/seed/asiance-wellness-1/1200/760',
    authorName: 'Asiance Editors',
    tags: ['wellbeing', 'ritual', 'health'],
    discussionCount: 47,
    featured: true,
  },
  {
    title: 'The sweater superlatives: 15 of spring’s most notable knits',
    slug: 'spring-knit-superlatives',
    category: 'Fashion & Beauty',
    excerpt: 'A soft, luxurious knit remains one of our greatest sartorial delights.',
    content:
      'This spring’s knits are lighter, cleaner, and quietly detailed: ribbed cardigans, open-weave pullovers, and the kind of cotton crewneck that lives beside a swimsuit or a tailored trouser.',
    image: 'https://picsum.photos/seed/asiance-knit-1/1200/760',
    authorName: 'Marie Schmidt',
    tags: ['fashion', 'spring'],
    discussionCount: 22,
    featured: true,
  },

  {
    title: 'Meet fashion’s new it sneaker',
    slug: 'fashion-new-it-sneaker',
    category: 'Lifestyle',
    excerpt: 'The shoe making tailored trousers, denim, and airy dresses feel newly practical.',
    content:
      'The new sneaker is less technical and more architectural: low-profile, tonal, and just structured enough to make a simple outfit feel intentional.',
    image: 'https://picsum.photos/seed/asiance-shoes-1/1200/760',
    authorName: 'Iris Halden',
    tags: ['fashion', 'lifestyle'],
    discussionCount: 33,
  },
];

export const articleCategories = [
  { name: 'Lifestyle', slug: 'lifestyle', sortOrder: 0 },
  { name: 'Fashion and Beauty', slug: 'fashion-beauty', sortOrder: 1 },
  { name: 'Sex and Health', slug: 'sex-health', sortOrder: 2 },
  { name: 'Interiors', slug: 'interiors', sortOrder: 3 },
  { name: 'Travel', slug: 'travel', sortOrder: 4 },
  { name: 'Weddings', slug: 'weddings', sortOrder: 8 },
  { name: 'Family', slug: 'family', sortOrder: 9 },
  { name: 'Relationships', slug: 'relationships', sortOrder: 10 },
];

export const newsCategories: NewsCategory[] = [
  { name: 'Beauty', slug: 'beauty', image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640141/asiance/site-assets/categories/beauty-png.png', sortOrder: 0 },
  { name: 'Fashion', slug: 'fashion', image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640141/asiance/site-assets/categories/fashion-png.png', sortOrder: 1 },
  { name: 'Dating', slug: 'dating', image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640142/asiance/site-assets/categories/dating-png.png', sortOrder: 2 },
  { name: 'Weddings', slug: 'weddings', image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640148/asiance/site-assets/categories/weddings-png.png', sortOrder: 3 },
  { name: 'Baby', slug: 'baby', image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640139/asiance/site-assets/categories/baby-png.png', sortOrder: 4 },
  { name: 'Kids', slug: 'kids', image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640145/asiance/site-assets/categories/kids-png.png', sortOrder: 5 },
  { name: 'Travel', slug: 'travel', image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640145/asiance/site-assets/categories/travel-png.png', sortOrder: 6 },
  { name: 'Home', slug: 'home', image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640146/asiance/site-assets/categories/home-png.png', sortOrder: 7 },
  { name: 'Food', slug: 'food', image: 'https://res.cloudinary.com/ux81wsbq/image/upload/v1786640143/asiance/site-assets/categories/food-png.png', sortOrder: 8 },
];

export const newsItems: NewsItem[] = [
  {
    title: 'Asiance opens a weekly editor briefing for members',
    slug: 'asiance-weekly-editor-briefing',
    categoryName: 'Beauty',
    categorySlug: 'beauty',
    excerpt:
      'A tighter Monday digest will collect community highlights, product drops, and editorial notes in one place.',
    content:
      'The weekly editor briefing is designed as a single useful signal: new stories, active conversations, shop notes, and category updates from the Asiance team.',
    image: 'https://picsum.photos/seed/asiance-news-digest/1200/760',
    authorName: 'Asiance Editors',
    tags: ['community', 'editorial'],
    featured: true,
    breaking: true,
    sourceName: 'Asiance',
    sourceUrl: 'https://asiance.co',
    status: 'published',
  },
  {
    title: 'Five transportive novels that will take you somewhere else',
    slug: 'transportive-novels-news',
    categoryName: 'Fashion',
    categorySlug: 'fashion',
    excerpt: 'A reading list for long flights, quiet weekends, and the soft hour before sleep.',
    content:
      'The best travel reading does not always involve a map. These novels move by mood: humid kitchens, train platforms, islands, hotels, and private weather.',
    image: 'https://picsum.photos/seed/asiance-books-news/1200/760',
    authorName: 'jack',
    tags: ['books', 'culture'],
    featured: false,
    breaking: false,
    sourceName: 'Asiance Culture',
    status: 'published',
  },
  {
    title: 'The sweater superlatives: spring knits worth noting',
    slug: 'spring-knit-superlatives-news',
    categoryName: 'Dating',
    categorySlug: 'dating',
    excerpt: 'A soft, luxurious knit remains one of our quietest sartorial delights.',
    content:
      'This season leans into ribbed cardigans, open-weave pullovers, and cotton crewnecks that work beside swimsuits or tailored trousers.',
    image: 'https://picsum.photos/seed/asiance-knit-news/1200/760',
    authorName: 'Marie Schmidt',
    tags: ['fashion', 'spring'],
    featured: true,
    breaking: false,
    sourceName: 'Asiance Style',
    status: 'published',
  },
  {
    title: 'Should you try gentle contrast therapy?',
    slug: 'gentle-contrast-therapy-news',
    categoryName: 'Weddings',
    categorySlug: 'weddings',
    excerpt:
      'A measured guide to hot, cold, and the ritual in between, with notes from bathhouse founders and clinicians.',
    content:
      'Contrast therapy has become a social ritual as much as a recovery tool. Start gently, keep temperature shifts moderate, and listen closely to your body.',
    image: 'https://picsum.photos/seed/asiance-wellness-news/1200/760',
    authorName: 'Asiance Editors',
    tags: ['wellbeing', 'health'],
    featured: false,
    breaking: false,
    sourceName: 'Asiance Health',
    status: 'published',
  },
  {
    title: 'Meet fashion new low-profile sneaker mood',
    slug: 'fashion-new-sneaker-mood',
    categoryName: 'Baby',
    categorySlug: 'baby',
    excerpt: 'The shoe making tailored trousers, denim, and airy dresses feel newly practical.',
    content:
      'The new sneaker is less technical and more architectural: low-profile, tonal, and structured enough to make simple outfits feel intentional.',
    image: 'https://picsum.photos/seed/asiance-shoes-news/1200/760',
    authorName: 'Iris Halden',
    tags: ['fashion', 'lifestyle'],
    featured: false,
    breaking: true,
    sourceName: 'Asiance Lifestyle',
    status: 'published',
  },
  {
    title: 'A quieter way to test new wellness tech',
    slug: 'quieter-way-to-test-wellness-tech',
    categoryName: 'Kids',
    categorySlug: 'kids',
    excerpt: 'Small devices, fewer dashboards, and metrics that actually change a daily ritual.',
    content:
      'The best wellness technology disappears into a routine. Our editors look for devices that reduce friction rather than create another screen to manage.',
    image: 'https://picsum.photos/seed/asiance-tech-news/1200/760',
    authorName: 'Asiance Editors',
    tags: ['tech', 'wellbeing'],
    featured: false,
    breaking: false,
    sourceName: 'Asiance Tech',
    status: 'published',
  },
];

export const groups: Group[] = [
  {
    name: 'The Morning Circle',
    slug: 'the-morning-circle',
    category: 'Rituals',
    privacy: 'private',
    description: 'Coffee, cold water, stretching, journaling, and the tiny decisions that set a day.',
    image: 'https://picsum.photos/seed/asiance-circle-morning/900/600',
    membersCount: 312,
    tags: ['ritual', 'morning'],
  },
  {
    name: 'Quiet Interiors',
    slug: 'quiet-interiors',
    category: 'Home',
    privacy: 'public',
    description: 'Rooms with restraint: linen, paper lamps, stone, wood, books, and useful emptiness.',
    image: 'https://picsum.photos/seed/asiance-circle-interiors/900/600',
    membersCount: 540,
    tags: ['home', 'objects'],
  },
  {
    name: 'Slow Ferments',
    slug: 'slow-ferments',
    category: 'Food',
    privacy: 'public',
    description: 'Kimchi, koji, sourdough, shrubs, pickles, and patient kitchen experiments.',
    image: 'https://picsum.photos/seed/asiance-circle-ferments/900/600',
    membersCount: 128,
    tags: ['food', 'wellbeing'],
  },
  {
    name: 'Archival Denim',
    slug: 'archival-denim',
    category: 'Fashion',
    privacy: 'public',
    description: 'Fits, repairs, fades, vintage sources, and denim that improves by living.',
    image: 'https://picsum.photos/seed/asiance-circle-denim/900/600',
    membersCount: 221,
    tags: ['fashion'],
  },
  {
    name: 'Bathhouse Club',
    slug: 'bathhouse-club',
    category: 'Wellbeing',
    privacy: 'public',
    description: 'Saunas, steam, cold plunges, etiquette, playlists, and recovery rituals.',
    image: 'https://picsum.photos/seed/asiance-circle-bathhouse/900/600',
    membersCount: 86,
    tags: ['health', 'ritual'],
  },
  {
    name: 'newyork Rituals',
    slug: 'karachi-rituals',
    category: 'Local',
    privacy: 'public',
    description: 'Chai houses, fabric markets, evening walks, and city notes from Karachi members.',
    image: 'https://picsum.photos/seed/asiance-circle-karachi/900/600',
    membersCount: 47,
    tags: ['karachi', 'local'],
  },
];

export const members: Member[] = [
  {
    name: 'Mira Tanaka',
    email: 'mira@asiance.co',
    handle: 'miratanaka',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Mira%20Tanaka',
    bio: 'Ceramics, morning walks, quiet hotels, and long-form beauty writing.',
    location: 'Kyoto, Japan',
    status: 'active 3 minutes ago',
    interests: ['objects', 'travel', 'ritual'],
  },
  {
    name: 'jack',
    email: 'noor@asiance.co',
    handle: 'jack',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Noor%20Aziz',
    bio: 'Karachi-based reader, event host, and collector of excellent cotton.',
    location: 'Karachi, Pakistan',
    status: 'active 20 minutes ago',
    interests: ['fashion', 'books', 'local'],
  },
  {
    name: 'Iris Halden',
    email: 'iris@asiance.co',
    handle: 'irishalden',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Iris%20Halden',
    bio: 'Fermentation notes, interior references, and too many linen shirts.',
    location: 'Copenhagen, Denmark',
    status: 'active 2 hours ago',
    interests: ['food', 'interiors'],
  },
  {
    name: 'Lea Moreau',
    email: 'lea@asiance.co',
    handle: 'leamoreau',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Lea%20Moreau',
    bio: 'Objects, gardens, and slow city guides.',
    location: 'Paris, France',
    status: 'active yesterday',
    interests: ['travel', 'home'],
  },
  {
    name: 'Sana Farooq',
    email: 'sana@asiance.co',
    handle: 'sanafarooq',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Sana%20Farooq',
    bio: 'Beauty editor, sunscreen evangelist, and market wanderer.',
    location: 'Lahore, Pakistan',
    status: 'active 1 day ago',
    interests: ['beauty', 'local'],
  },
  {
    name: 'Yuna Park',
    email: 'yuna@asiance.co',
    handle: 'yunapark',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Yuna%20Park',
    bio: 'Interiors, small brands, and weekend baths.',
    location: 'Seoul, Korea',
    status: 'active 3 days ago',
    interests: ['home', 'wellbeing'],
  },
];

export const activity: Activity[] = [
  {
    actorName: 'Mira Tanaka',
    actorHandle: 'miratanaka',
    type: 'post',
    text: 'A grey Kyoto morning. Hot water, a slow pour, and the new ceramic carafe is exactly right in the hand.',
    targetName: 'The Morning Circle',
    targetSlug: 'the-morning-circle',
    likes: 42,
    comments: 8,
    media: [{ type: 'image', url: 'https://picsum.photos/seed/asiance-activity-1/900/600', caption: 'Kyoto morning ritual' }],
  },
  {
    actorName: 'Iris Halden',
    actorHandle: 'irishalden',
    type: 'thread',
    text: 'started a thread on countertop ferments that do not take over the whole apartment.',
    targetName: 'Slow Ferments',
    targetSlug: 'slow-ferments',
    likes: 18,
    comments: 14,
    media: [{ type: 'image', url: 'https://picsum.photos/seed/asiance-activity-2/900/600', caption: 'Countertop ferments' }],
  },
  {
    actorName: 'jack',
    actorHandle: 'jack',
    type: 'comment',
    text: 'left a note on gentle contrast therapy: start softer than you think.',
    targetName: 'Gentle Contrast Therapy',
    targetSlug: 'gentle-contrast-therapy',
    likes: 23,
    comments: 4,
  },
];

export const threads: ForumThread[] = [
  {
    title: 'What makes a morning ritual actually last?',
    slug: 'what-makes-a-morning-ritual-last',
    category: 'Rituals',
    groupSlug: 'the-morning-circle',
    authorName: 'Mira Tanaka',
    excerpt: 'Tiny repeatable steps, generous timing, and not making the routine too precious.',
    replies: 34,
    pinned: true,
  },
  {
    title: 'Favorite low-light lamps for rented apartments',
    slug: 'favorite-low-light-lamps',
    category: 'Home',
    groupSlug: 'quiet-interiors',
    authorName: 'Iris Halden',
    excerpt: 'Looking for warm pools of light, no electrician required.',
    replies: 19,
  },
  {
    title: 'Karachi fabric market route for first-timers',
    slug: 'karachi-fabric-market-route',
    category: 'Local',
    groupSlug: 'karachi-rituals',
    authorName: 'jack',
    excerpt: 'A gentle half-day route with tea stops and trusted shops.',
    replies: 11,
  },
];

export const files: FileAsset[] = [
  {
    title: 'Spring lookbook notes',
    type: 'doc',
    category: 'Editorial',
    size: '88 KB',
    ownerName: 'Asiance Editors',
  },
  {
    title: 'Kyoto pop-up moodboard',
    type: 'media',
    category: 'Events',
    size: '42 MB',
    ownerName: 'Mira Tanaka',
  },
  {
    title: 'Community launch checklist',
    type: 'file',
    category: 'Operations',
    size: '19 KB',
    ownerName: 'Admin',
  },
];
